apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      env: blue
  template:
    metadata:
      labels:
        app: notification-service
        env: blue
    spec:
      containers:
      - name: notification-service
        image: ranaliw/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: healthsync-db-credentials  
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: healthsync-db-credentials 
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthsync-db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: healthsync-db-credentials
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-blue
spec:
  selector:
    app: notification-service
    env: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
